#!/usr/bin/env node
// @ts-check
/**
 * tool/golden/scaffold.mjs — golden-parity scaffolder (golden-parity WBS §4b).
 *
 * Reads the SINGLE SOURCE OF TRUTH `docs/design/screen-state-matrix.md` (every
 * screen × state) and generates the golden-test skeleton so a state can never be
 * silently missed:
 *   - test/fixtures/<screen>/<screen>_<state>_fixture.dart   (fail-by-default stub)
 *   - test/fixtures/<screen>/<screen>_fixtures.dart          (barrel — regenerated)
 *   - test/fixtures/state_registry.dart                      (registry — regenerated)
 *
 * Per-state fixture files are CREATE-IF-MISSING (never overwritten), so filled
 * logic is safe on re-run and a new kit state just grows one new stub. Barrels +
 * registry are pure aggregation → always regenerated deterministically.
 *
 * The golden TEST files (test/golden/screens/<screen>/) are generated in a later
 * step (they need a screen→widget map); this pass owns fixtures + coverage.
 *
 * Usage:
 *   node tool/golden/scaffold.mjs            # create missing stubs + regen barrels/registry
 *   node tool/golden/scaffold.mjs --check    # fail if matrix ↔ fixtures drift (gate)
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const MATRIX = join(REPO, 'docs', 'design', 'screen-state-matrix.md');
const FIX_DIR = join(REPO, 'test', 'fixtures');
const GOLDEN_DIR = join(REPO, 'test', 'golden', 'screens');
const CHECK = process.argv.includes('--check');

const GEN = '// GENERATED by tool/golden/scaffold.mjs';

// Screen → widget under test. All 21 screens follow the convention
// lib/presentation/features/<screen>/screens/<snake>_screen.dart · <Pascal>Screen
// with a zero-arg `const` ctor — EXCEPT the ones below that need a route arg.
// { expr } overrides the constructor call; { imports } adds extra imports.
const WIDGET_EXCEPTIONS = {
  'deck-detail': {
    expr: "const DeckDetailScreen(deckId: 'deck-root')",
    imports: [],
  },
};

// ── parse the matrix ────────────────────────────────────────────────────────
/** @returns {{screen:string, states:string[]}[]} in document order. */
function parseMatrix() {
  const lines = readFileSync(MATRIX, 'utf8').split('\n');
  /** @type {{screen:string, states:string[]}[]} */
  const out = [];
  let cur = null;
  const headRe = /^##\s+S\.\d+\s+·\s+([a-z0-9-]+)/; // only `## S.NN · <screen>`
  const rowRe = /^\|\s*`([a-z0-9-]+)`\s*\|/; // `| `state` | …`
  for (const line of lines) {
    if (line.startsWith('## ')) {
      const m = line.match(headRe);
      // Any non-screen `## ` header (e.g. "Canonical state kinds") ends the
      // current screen so its legend table is never mistaken for states.
      cur = m ? { screen: m[1], states: [] } : null;
      if (cur) out.push(cur);
      continue;
    }
    if (!cur) continue;
    const m = line.match(rowRe);
    if (m) cur.states.push(m[1]);
  }
  return out;
}

// ── naming helpers ──────────────────────────────────────────────────────────
const snake = (id) => id.replace(/-/g, '_');
const pascal = (id) => id.split('-').map((p) => p[0].toUpperCase() + p.slice(1)).join('');
const camel = (id) => { const p = pascal(id); return p[0].toLowerCase() + p.slice(1); };
const fixtureVar = (screen, state) => `${camel(screen)}${pascal(state)}Fixture`;
const fixtureFile = (screen, state) => `${snake(screen)}_${snake(state)}_fixture.dart`;
const barrelFile = (screen) => `${snake(screen)}_fixtures.dart`;

// ── generators ──────────────────────────────────────────────────────────────
function stubSource(screen, state) {
  const v = fixtureVar(screen, state);
  return (
    `${GEN} — then FILLED BY HAND. Once you replace the sentinel below with a\n` +
    `// real StateFixture, the scaffolder leaves this file untouched on re-run.\n` +
    `// ${screen} · ${state} — golden-parity fixture (docs/agent/golden-parity/WBS.md).\n` +
    `import '../_fixture.dart';\n\n` +
    `// FILL(golden-parity): replace the sentinel with a real StateFixture(overrides, drive, contentMask).\n` +
    `const StateFixture ${v} = StateFixture.unimplemented('${screen}/${state}');\n`
  );
}

function barrelSource(screen, states) {
  const imports = states
    .map((s) => `import '${fixtureFile(screen, s)}';`)
    .sort()
    .join('\n');
  const entries = states
    .map((s) => `  '${s}': ${fixtureVar(screen, s)},`)
    .join('\n');
  return (
    `${GEN} — DO NOT EDIT (pure aggregation; re-run the scaffolder).\n` +
    `import '../_fixture.dart';\n${imports}\n\n` +
    `/// State fixtures for the ${screen} screen, keyed by matrix state name.\n` +
    `final Map<String, StateFixture> ${camel(screen)}Fixtures = {\n${entries}\n};\n`
  );
}

function goldenTestSource(screen, states) {
  const ex = WIDGET_EXCEPTIONS[screen];
  const widgetClass = `${pascal(screen)}Screen`;
  const widgetExpr = ex ? ex.expr : `const ${widgetClass}()`;
  const screenImport = `import 'package:memox_v4/presentation/features/${screen}/screens/${snake(screen)}_screen.dart';`;
  const extra = ex ? ex.imports.join('\n') : '';
  const imports = [
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_test/flutter_test.dart';",
    "import 'package:memox_v4/core/theme/app_theme.dart';",
    screenImport,
    extra,
    `import '../../../fixtures/${screen}/${barrelFile(screen)}';`,
    "import '../../support/screen_golden.dart';",
  ].filter(Boolean).join('\n');
  return (
    `${GEN} — golden test (create-if-missing; safe to edit after generation).\n` +
    `@Tags(['golden-parity'])\n` +
    `library;\n\n` +
    `${imports}\n\n` +
    `/// Screen goldens for ${screen} — one per state × theme, driven by the\n` +
    `/// state fixtures. Tagged 'golden-parity' (excluded from the default gate;\n` +
    `/// a dedicated CI job owns the baselines). Un-filled fixtures fail fast.\n` +
    `void main() {\n` +
    `  final themes = <String, ThemeData>{'light': AppTheme.light, 'dark': AppTheme.dark};\n` +
    `  ${camel(screen)}Fixtures.forEach((state, fixture) {\n` +
    `    themes.forEach((theme, data) {\n` +
    `      testWidgets('${screen}--\$state--\$theme', (tester) async {\n` +
    `        await pumpScreenGolden(tester, home: ${widgetExpr}, fixture: fixture, theme: data);\n` +
    `        await expectLater(\n` +
    `          find.byType(MaterialApp),\n` +
    `          matchesGoldenFile('../../goldens/screens/${screen}--\$state--\$theme.png'),\n` +
    `        );\n` +
    `      });\n` +
    `    });\n` +
    `  });\n` +
    `}\n`
  );
}

function registrySource(screens) {
  const imports = screens
    .map((s) => `import '${s.screen}/${barrelFile(s.screen)}';`)
    .sort()
    .join('\n');
  const entries = screens
    .map((s) => `  '${s.screen}': ${camel(s.screen)}Fixtures,`)
    .join('\n');
  return (
    `${GEN} — DO NOT EDIT (pure aggregation; re-run the scaffolder).\n` +
    `import '_fixture.dart';\n${imports}\n\n` +
    `/// screen id → { state name → StateFixture }. Source of truth:\n` +
    `/// docs/design/screen-state-matrix.md (via tool/golden/scaffold.mjs).\n` +
    `final Map<String, Map<String, StateFixture>> stateRegistry = {\n${entries}\n};\n`
  );
}

// ── --check: matrix ↔ fixtures coverage ─────────────────────────────────────
function check(screens) {
  const problems = [];
  const matrixSet = new Set();
  for (const { screen, states } of screens) {
    for (const state of states) {
      matrixSet.add(`${screen}/${state}`);
      const f = join(FIX_DIR, screen, fixtureFile(screen, state));
      if (!existsSync(f)) problems.push(`MISSING fixture: ${screen}/${state} (${fixtureFile(screen, state)})`);
    }
    const gt = join(GOLDEN_DIR, screen, `${snake(screen)}_golden_test.dart`);
    if (!existsSync(gt)) problems.push(`MISSING golden test: ${screen} (${snake(screen)}_golden_test.dart)`);
  }
  // Orphans: fixture files with no matching matrix state.
  if (existsSync(FIX_DIR)) {
    for (const screen of readdirSync(FIX_DIR)) {
      const dir = join(FIX_DIR, screen);
      if (!existsSync(dir) || !readdirSync.length) continue;
      let entries;
      try { entries = readdirSync(dir); } catch { continue; }
      for (const file of entries) {
        if (!file.endsWith('_fixture.dart')) continue;
        // reverse: <screen>_<state>_fixture.dart — state is the middle, but both
        // screen and state may contain underscores, so match against the matrix.
        const known = [...matrixSet].some((k) => {
          const [scr, st] = k.split('/');
          return scr === screen && fixtureFile(scr, st) === file;
        });
        if (!known) problems.push(`ORPHAN fixture: ${screen}/${file} — no matrix state`);
      }
    }
  }
  if (problems.length) {
    console.error(`✗ scaffold --check: ${problems.length} matrix↔fixture drift:`);
    for (const p of problems) console.error('  ' + p);
    process.exit(1);
  }
  console.log(`✓ scaffold --check: ${matrixSet.size} states across ${screens.length} screens — all fixtures present, no orphans`);
}

// ── run ─────────────────────────────────────────────────────────────────────
const screens = parseMatrix();
if (!screens.length) {
  console.error('✗ scaffold: parsed 0 screens from the matrix — check the format.');
  process.exit(2);
}

if (CHECK) {
  check(screens);
  process.exit(0);
}

let created = 0;
for (const { screen, states } of screens) {
  const dir = join(FIX_DIR, screen);
  mkdirSync(dir, { recursive: true });
  for (const state of states) {
    const f = join(dir, fixtureFile(screen, state));
    if (!existsSync(f)) { writeFileSync(f, stubSource(screen, state), 'utf8'); created++; }
  }
  writeFileSync(join(dir, barrelFile(screen)), barrelSource(screen, states), 'utf8');
  // Golden test — create-if-missing (it's editable after generation).
  const gdir = join(GOLDEN_DIR, screen);
  mkdirSync(gdir, { recursive: true });
  const gt = join(gdir, `${snake(screen)}_golden_test.dart`);
  if (!existsSync(gt)) { writeFileSync(gt, goldenTestSource(screen, states), 'utf8'); created++; }
}
writeFileSync(join(FIX_DIR, 'state_registry.dart'), registrySource(screens), 'utf8');

const total = screens.reduce((n, s) => n + s.states.length, 0);
console.log(`✓ scaffold: ${screens.length} screens · ${total} states · ${created} new stub(s) created; barrels + registry regenerated`);
