// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'review_audio_fixture.dart';
import 'review_browsing_fixture.dart';
import 'review_editing_fixture.dart';
import 'review_end_fixture.dart';

/// State fixtures for the review screen, keyed by matrix state name.
final Map<String, StateFixture> reviewFixtures = {
  'browsing': reviewBrowsingFixture,
  'audio': reviewAudioFixture,
  'editing': reviewEditingFixture,
  'end': reviewEndFixture,
};
