// GENERATED by tool/golden/scaffold.mjs — golden test (create-if-missing; safe to edit after generation).
@Tags(['golden-parity'])
library;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:memox_v4/core/routes/app_routes.dart';
import 'package:memox_v4/core/theme/app_theme.dart';
import 'package:memox_v4/presentation/features/statistics/screens/statistics_screen.dart';
import '../../../fixtures/statistics/statistics_fixtures.dart';
import '../../support/screen_golden.dart';

/// Screen goldens for statistics — one per state × theme, driven by the
/// state fixtures. Tagged 'golden-parity' (excluded from the default gate;
/// a dedicated CI job owns the baselines). Un-filled fixtures fail fast.
void main() {
  final themes = <String, ThemeData>{
    'light': AppTheme.light,
    'dark': AppTheme.dark,
  };
  statisticsFixtures.forEach((state, fixture) {
    themes.forEach((theme, data) {
      testWidgets('statistics--$state--$theme', (tester) async {
        await pumpScreenGolden(
          tester,
          home: const StatisticsScreen(),
          fixture: fixture,
          theme: data,
          shellTab: AppTab.stats,
        );
        await expectLater(
          find.byType(MaterialApp),
          matchesGoldenFile(
            '../../goldens/screens/statistics--$state--$theme.png',
          ),
        );
      });
    });
  });
}
