// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'game_matching_almost_fixture.dart';
import 'game_matching_complete_fixture.dart';
import 'game_matching_correct_fixture.dart';
import 'game_matching_playing_fixture.dart';
import 'game_matching_selected_fixture.dart';
import 'game_matching_wrong_fixture.dart';

/// State fixtures for the game-matching screen, keyed by matrix state name.
final Map<String, StateFixture> gameMatchingFixtures = {
  'playing': gameMatchingPlayingFixture,
  'selected': gameMatchingSelectedFixture,
  'correct': gameMatchingCorrectFixture,
  'wrong': gameMatchingWrongFixture,
  'almost': gameMatchingAlmostFixture,
  'complete': gameMatchingCompleteFixture,
};
