#!/usr/bin/env node
// @ts-check
/**
 * gen_tokens.mjs — Tier-0 design-token generator.
 *
 * Reads the FROZEN CSS token files (the design kit's single source of truth,
 * per `docs/design/MemoX Design System/readme.md`) and emits their Dart
 * mirrors under `lib/core/theme/`. This replaces the hand-typed token layer:
 * a token VALUE change in the kit becomes a one-command regeneration here,
 * with zero manual transcription and no AI cost per token.
 *
 * Source of truth is the CSS, NOT `_ds_manifest.json` — the manifest only
 * covers the files in its `globalCssPaths` (colors/typography/spacing/radius/
 * elevation) and silently omits size.css / icon-size.css / stroke.css /
 * motion.css and the `--memox-palette-*` accents. Parsing CSS is complete.
 *
 * Drift guard: every `--memox-*` custom property parsed from the CSS must be
 * consumed by exactly one emitter (or be in SKIP). An unconsumed token aborts
 * the run — so a new kit token can never slip in unmirrored and unnoticed.
 *
 * Usage:  node tool/design/gen_tokens.mjs            (writes files)
 *         node tool/design/gen_tokens.mjs --check    (fails if out of date)
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const TOKENS_DIR = join(REPO, 'docs', 'design', 'MemoX Design System', 'tokens');
const OUT_DIR = join(REPO, 'lib', 'core', 'theme');
const CHECK = process.argv.includes('--check');

const GEN_HEADER = (source) =>
  `// GENERATED by tool/design/gen_tokens.mjs — DO NOT EDIT BY HAND.\n` +
  `// Source of truth: docs/design/MemoX Design System/tokens/${source}\n` +
  `// Regenerate: node tool/design/gen_tokens.mjs\n`;

// ── CSS parsing ─────────────────────────────────────────────────────────────
/** @typedef {{name:string, value:string, scope:'light'|'dark'}} Decl */

/** Strip /* *​/ comments, then pull `selectors { decls }` blocks. */
function parseCss(css) {
  const noComments = css.replace(/\/\*[\s\S]*?\*\//g, '');
  /** @type {Decl[]} */
  const out = [];
  const blockRe = /([^{}]+)\{([^{}]*)\}/g;
  let m;
  while ((m = blockRe.exec(noComments))) {
    const selector = m[1].trim();
    if (selector.startsWith('@')) continue; // @font-face etc.
    const scope = /\[data-theme=['"]dark['"]\]/.test(selector) ? 'dark' : 'light';
    const body = m[2];
    const declRe = /(--memox-[a-z0-9-]+)\s*:\s*([^;]+);/g;
    let d;
    while ((d = declRe.exec(body))) {
      out.push({ name: d[1], value: d[2].trim().replace(/\s+/g, ' '), scope });
    }
  }
  return out;
}

/** name -> { light?:string, dark?:string } */
const TOK = new Map();
const CONSUMED = new Set();

function loadTokens() {
  for (const file of readdirSync(TOKENS_DIR).filter((f) => f.endsWith('.css'))) {
    for (const { name, value, scope } of parseCss(readFileSync(join(TOKENS_DIR, file), 'utf8'))) {
      const e = TOK.get(name) || {};
      e[scope] = value;
      e._file = file;
      TOK.set(name, e);
    }
  }
}

// ── value converters ────────────────────────────────────────────────────────
/** CSS color (#hex / rgb() / rgba()) -> Dart `Color(0xAARRGGBB)`. */
function color(v) {
  v = v.trim();
  let r, g, b, a = 255;
  let m = v.match(/^#([0-9a-fA-F]{3,8})$/);
  if (m) {
    let h = m[1];
    if (h.length === 3) h = h.split('').map((c) => c + c).join('');
    if (h.length === 6) { r = p(h, 0); g = p(h, 2); b = p(h, 4); }
    else if (h.length === 8) { r = p(h, 0); g = p(h, 2); b = p(h, 4); a = p(h, 6); }
    else throw new Error(`bad hex: ${v}`);
  } else if ((m = v.match(/^rgba?\(([^)]+)\)$/))) {
    const parts = m[1].split(',').map((s) => s.trim());
    r = +parts[0]; g = +parts[1]; b = +parts[2];
    a = parts[3] === undefined ? 255 : Math.round(parseFloat(parts[3]) * 255);
  } else {
    throw new Error(`not a color: ${v}`);
  }
  const hex = (n) => n.toString(16).toUpperCase().padStart(2, '0');
  return `Color(0x${hex(a)}${hex(r)}${hex(g)}${hex(b)})`;
  function p(h, i) { return parseInt(h.slice(i, i + 2), 16); }
}

/** `16px` | `0` -> number (logical px). */
function px(v) {
  const m = v.trim().match(/^(-?[\d.]+)px$/);
  if (m) return +m[1];
  if (v.trim() === '0') return 0;
  const n = Number(v.trim());
  if (!Number.isNaN(n)) return n;
  throw new Error(`not a px value: ${v}`);
}

/** `-0.02em` | `0` -> number (em multiplier). */
function em(v) {
  const t = v.trim();
  if (t === '0') return 0;
  const m = t.match(/^(-?[\d.]+)em$/);
  if (m) return +m[1];
  const n = Number(t);
  if (!Number.isNaN(n)) return n;
  throw new Error(`not an em value: ${v}`);
}

/** trim trailing `.0`-free but keep it a Dart double literal. */
function dbl(n) {
  return Number.isInteger(n) ? `${n}` : `${n}`;
}

// ── token accessors (mark consumed) ─────────────────────────────────────────
function get(name) {
  const e = TOK.get(name);
  if (!e) throw new Error(`missing token: ${name}`);
  CONSUMED.add(name);
  return e;
}
function lightOf(name) { return get(name).light; }
function isThemed(name) { const e = get(name); return e.dark !== undefined; }

/** All parsed token names matching a prefix, in first-seen order. */
function namesWith(prefix) {
  return [...TOK.keys()].filter((n) => n.startsWith(prefix));
}

// ── name helpers ────────────────────────────────────────────────────────────
const cap = (s) => (s.length ? s[0].toUpperCase() + s.slice(1) : s);
/** `surface-muted` -> `surfaceMuted`. */
const camel = (s) => s.split('-').map((p, i) => (i ? cap(p) : p)).join('');

// ── emitters ────────────────────────────────────────────────────────────────
/** @type {Record<string,string>} */
const FILES = {};

function emitColors() {
  // Every color-valued, theme-varying token from colors.css, in CSS order.
  const themed = namesWith('--memox-')
    .filter((n) => { const e = TOK.get(n); return e._file === 'colors.css' && e.dark !== undefined; });
  const fields = themed.map((n) => ({ dart: camel(n.replace('--memox-', '')), name: n }));

  const ctorArgs = fields.map((f) => `    required this.${f.dart},`).join('\n');
  const decls = fields.map((f) => `  final Color ${f.dart};`).join('\n');
  const instance = (scope) =>
    fields.map((f) => `    ${f.dart}: ${color(get(f.name)[scope])},`).join('\n');

  // Accent palette — root-only (theme-independent) picker hues.
  const palette = namesWith('--memox-palette-').map((n) => {
    const dart = camel(n.replace('--memox-', ''));
    return `  static const Color ${dart} = ${color(lightOf(n))};`;
  }).join('\n');

  FILES['mx_colors.dart'] =
    GEN_HEADER('colors.css') +
    `import 'package:flutter/widgets.dart';\n\n` +
    `/// Semantic color palette for one brightness, mirroring \`--memox-<role>\`\n` +
    `/// in \`tokens/colors.css\`. One [MxColors] per theme: [light] and [dark].\n` +
    `///\n` +
    `/// Features read colors from the theme, never raw \`Color(0x...)\`. The roles\n` +
    `/// Material's [ColorScheme] cannot express are surfaced via a theme extension\n` +
    `/// (Tier 1); the rest seed the [ColorScheme].\n` +
    `@immutable\n` +
    `class MxColors {\n` +
    `  const MxColors({\n${ctorArgs}\n  });\n\n` +
    `${decls}\n\n` +
    `  /// Brand primary seed (\`--memox-primary\`, light).\n` +
    `  static const Color seed = ${color(lightOf('--memox-primary'))};\n\n` +
    `  // Selectable accent hues (theme-independent) — \`--memox-palette-*\`.\n` +
    `${palette}\n\n` +
    `  /// Light — \`:root\` / \`[data-theme='light']\`.\n` +
    `  static const MxColors light = MxColors(\n${instance('light')}\n  );\n\n` +
    `  /// Dark — \`[data-theme='dark']\`.\n` +
    `  static const MxColors dark = MxColors(\n${instance('dark')}\n  );\n}\n`;
}

function emitSpacing() {
  const scale = namesWith('--memox-space-')
    .map((n) => `  static const double space${n.replace('--memox-space-', '')} = ${dbl(px(lightOf(n)))};`)
    .join('\n');
  // Curated semantic aliases (word order differs from mechanical camelCase).
  const alias = [
    ['--memox-gutter', 'gutter', 'Screen edge padding on phones.'],
    ['--memox-appbar-height', 'appBarHeight', 'Compact top app bar.'],
    ['--memox-appbar-lg-height', 'appBarLargeHeight', 'Large / hero app bar.'],
    ['--memox-bottom-nav-height', 'bottomNavHeight', 'Fixed bottom navigation.'],
    ['--memox-fab-size', 'fabSize', 'Floating action button.'],
    ['--memox-touch-min', 'minTouchTarget', 'Minimum interactive target (a11y floor).'],
  ].map(([n, d, doc]) => `  /// ${doc}\n  static const double ${d} = ${dbl(px(lightOf(n)))};`).join('\n\n');

  FILES['mx_spacing.dart'] =
    GEN_HEADER('spacing.css') +
    `/// Spacing scale (4px base) + layout rhythm, mirroring \`--memox-space-*\`\n` +
    `/// and the layout tokens in \`tokens/spacing.css\`. Theme-independent.\n` +
    `abstract final class MxSpacing {\n` +
    `  const MxSpacing._();\n\n` +
    `${scale}\n\n` +
    `  // ── layout rhythm ─────────────────────────────────────────────────────────\n` +
    `${alias}\n}\n`;
}

function emitRadius() {
  const RMAP = { '2xl': 'xxl' }; // digit-leading suffix -> valid Dart id
  const rname = (suf) => RMAP[suf] || suf;
  const roles = ['card', 'tile', 'control', 'field', 'chip', 'pill', 'full'];
  const scaleSufs = ['xs', 'sm', 'md', 'lg', 'xl', '2xl'];

  const scale = scaleSufs
    .map((s) => `  static const double ${rname(s)} = ${dbl(px(lightOf(`--memox-radius-${s}`)))};`)
    .join('\n');
  const roleLines = roles
    .map((s) => `  static const double ${s} = ${dbl(px(lightOf(`--memox-radius-${s}`)))};`)
    .join('\n');
  const brFor = (role) =>
    `  static const BorderRadius ${role}Radius =\n      BorderRadius.all(Radius.circular(${role}));`;
  const helpers = ['card', 'tile', 'control', 'field', 'pill'].map(brFor).join('\n');

  FILES['mx_radius.dart'] =
    GEN_HEADER('radius.css') +
    `import 'package:flutter/widgets.dart';\n\n` +
    `/// Corner-radius scale + role aliases, mirroring \`--memox-radius-*\` in\n` +
    `/// \`tokens/radius.css\`. Raw \`double\` steps plus ready [BorderRadius] roles.\n` +
    `abstract final class MxRadius {\n` +
    `  const MxRadius._();\n\n` +
    `  // scale\n${scale}\n\n` +
    `  // role aliases\n${roleLines}\n\n` +
    `  // ── BorderRadius helpers ──────────────────────────────────────────────────\n` +
    `${helpers}\n}\n`;
}

function emitTypography() {
  const fam = lightOf('--memox-font-sans');
  const firstFamily = (fam.match(/'([^']+)'|^([^,]+)/) || [])[1] || 'Plus Jakarta Sans';
  get('--memox-font-mono'); // consume (mono not surfaced as a slot yet)

  const sizes = namesWith('--memox-font-size-')
    .map((n) => `  static const double size${cap(n.replace('--memox-font-size-', ''))} = ${dbl(px(lightOf(n)))};`)
    .join('\n');
  const weights = namesWith('--memox-font-weight-')
    .map((n) => { const s = n.replace('--memox-font-weight-', ''); return `  static const FontWeight ${s} = FontWeight.w${Number(lightOf(n))};`; })
    .join('\n');
  const lh = namesWith('--memox-line-height-')
    .map((n) => `  static const double lineHeight${cap(n.replace('--memox-line-height-', ''))} = ${dbl(Number(lightOf(n)))};`)
    .join('\n');
  const tr = namesWith('--memox-letter-spacing-')
    .map((n) => `  static const double tracking${cap(n.replace('--memox-letter-spacing-', ''))} = ${dbl(em(lightOf(n)))};`)
    .join('\n');

  FILES['mx_typography.dart'] =
    GEN_HEADER('typography.css') +
    `import 'package:flutter/widgets.dart';\n\n` +
    `/// Typography primitives, mirroring \`--memox-font-*\`, \`--memox-line-height-*\`\n` +
    `/// and \`--memox-letter-spacing-*\` in \`tokens/typography.css\`. Tier 1 composes\n` +
    `/// these into the Material [TextTheme].\n` +
    `///\n` +
    `/// Letter spacing is an **em multiplier** (the CSS unit); Flutter's\n` +
    `/// \`letterSpacing\` is logical px, so multiply by the slot size:\n` +
    `/// \`letterSpacing: size * MxTypography.trackingTight\`.\n` +
    `abstract final class MxTypography {\n` +
    `  const MxTypography._();\n\n` +
    `  /// Brand family (variable font under \`.../fonts/\`, wired via pubspec).\n` +
    `  static const String fontFamily = '${firstFamily}';\n\n` +
    `  // ── font sizes ────────────────────────────────────────────────────────────\n${sizes}\n\n` +
    `  // ── weights ───────────────────────────────────────────────────────────────\n${weights}\n\n` +
    `  // ── line heights (unitless -> Flutter \`height\`) ───────────────────────────\n${lh}\n\n` +
    `  // ── letter spacing (em multipliers — see class doc) ───────────────────────\n${tr}\n}\n`;
}

function emitSizes() {
  const sizeScale = namesWith('--memox-size-')
    .map((n) => `  static const double size${cap(n.replace('--memox-size-', ''))} = ${dbl(px(lightOf(n)))};`)
    .join('\n');
  const iconScale = namesWith('--memox-icon-size-')
    .map((n) => `  static const double ${n.replace('--memox-icon-size-', '')} = ${dbl(px(lightOf(n)))};`)
    .join('\n');
  const stroke = namesWith('--memox-stroke-')
    .map((n) => `  static const double ${n.replace('--memox-stroke-', '')} = ${dbl(px(lightOf(n)))};`)
    .join('\n');

  FILES['mx_sizes.dart'] =
    GEN_HEADER('size.css / icon-size.css / stroke.css') +
    `/// Fixed-dimension scales, mirroring \`--memox-size-*\`, \`--memox-icon-size-*\`\n` +
    `/// and \`--memox-stroke-*\`. Theme-independent.\n` +
    `library;\n\n` +
    `/// Element size scale (\`--memox-size-*\`).\n` +
    `abstract final class MxSizes {\n  const MxSizes._();\n\n${sizeScale}\n}\n\n` +
    `/// Icon glyph sizes (\`--memox-icon-size-*\`). 20/24 reuse the type scale.\n` +
    `abstract final class MxIconSize {\n  const MxIconSize._();\n\n${iconScale}\n}\n\n` +
    `/// Border / stroke widths (\`--memox-stroke-*\`).\n` +
    `abstract final class MxStroke {\n  const MxStroke._();\n\n${stroke}\n}\n`;
}

// CSS box-shadow -> Dart List<BoxShadow>. Splits top-level commas (layers),
// then leading dimension tokens (offx offy blur [spread]) + trailing color.
function boxShadow(css) {
  const layers = splitTop(css);
  const shadows = layers.map((layer) => {
    const colM = layer.match(/(rgba?\([^)]*\)|#[0-9a-fA-F]{3,8})\s*$/);
    if (!colM) throw new Error(`shadow layer has no color: ${layer}`);
    const col = color(colM[1]);
    const dims = layer.slice(0, colM.index).trim().split(/\s+/).map(px);
    const [ox = 0, oy = 0, blur = 0, spread = 0] = dims;
    const parts = [`color: ${col}`];
    if (ox !== 0 || oy !== 0) parts.push(`offset: Offset(${dbl(ox)}, ${dbl(oy)})`);
    if (blur !== 0) parts.push(`blurRadius: ${dbl(blur)}`);
    if (spread !== 0) parts.push(`spreadRadius: ${dbl(spread)}`);
    return `      BoxShadow(${parts.join(', ')}),`;
  });
  return `[\n${shadows.join('\n')}\n    ]`;

  function splitTop(s) {
    const out = []; let depth = 0, cur = '';
    for (const ch of s) {
      if (ch === '(') depth++;
      if (ch === ')') depth--;
      if (ch === ',' && depth === 0) { out.push(cur.trim()); cur = ''; }
      else cur += ch;
    }
    if (cur.trim()) out.push(cur.trim());
    return out;
  }
}

function emitElevation() {
  const roles = namesWith('--memox-shadow-').map((n) => ({ dart: camel(n.replace('--memox-shadow-', '')), name: n }));
  const ctorArgs = roles.map((r) => `    required this.${r.dart},`).join('\n');
  const decls = roles.map((r) => `  final List<BoxShadow> ${r.dart};`).join('\n');
  const instance = (scope) =>
    roles.map((r) => `    ${r.dart}: ${boxShadow(get(r.name)[scope])},`).join('\n');

  FILES['mx_elevation.dart'] =
    GEN_HEADER('elevation.css') +
    `import 'package:flutter/widgets.dart';\n\n` +
    `/// Elevation / shadow tokens, mirroring \`--memox-shadow-*\` in\n` +
    `/// \`tokens/elevation.css\`. Theme-dependent: soft blue-grey casts in light,\n` +
    `/// hairline ring + deep ambient in dark. The 4-value CSS rings (\`0 0 0 1px\`)\n` +
    `/// map to a zero-blur [BoxShadow] with \`spreadRadius: 1\`.\n` +
    `@immutable\n` +
    `class MxShadows {\n` +
    `  const MxShadows({\n${ctorArgs}\n  });\n\n` +
    `${decls}\n\n` +
    `  static const MxShadows light = MxShadows(\n${instance('light')}\n  );\n\n` +
    `  static const MxShadows dark = MxShadows(\n${instance('dark')}\n  );\n}\n`;
}

function emitMotion() {
  const durs = namesWith('--memox-duration-').map((n) => {
    const s = n.replace('--memox-duration-', '');
    const ms = Number(lightOf(n).replace('ms', ''));
    return `  static const Duration ${s} = Duration(milliseconds: ${ms});`;
  }).join('\n');
  const eases = namesWith('--memox-ease-').map((n) => {
    const s = camel(n.replace('--memox-ease-', ''));
    const m = lightOf(n).match(/cubic-bezier\(([^)]+)\)/);
    if (!m) throw new Error(`bad easing: ${lightOf(n)}`);
    const [a, b, c, d] = m[1].split(',').map((x) => dbl(parseFloat(x.trim())));
    return `  static const Cubic ${s} = Cubic(${a}, ${b}, ${c}, ${d});`;
  }).join('\n');

  FILES['mx_motion.dart'] =
    GEN_HEADER('motion.css') +
    `import 'package:flutter/animation.dart';\n\n` +
    `/// Motion tokens (durations + easings), mirroring \`--memox-duration-*\` and\n` +
    `/// \`--memox-ease-*\` in \`tokens/motion.css\`. Theme-independent.\n` +
    `abstract final class MxDurations {\n  const MxDurations._();\n\n${durs}\n}\n\n` +
    `/// Easing curves (\`--memox-ease-*\`): standard / decelerate (enter) /\n` +
    `/// accelerate (exit).\n` +
    `abstract final class MxEasing {\n  const MxEasing._();\n\n${eases}\n}\n`;
}

// ── coverage guard ──────────────────────────────────────────────────────────
// Compound/derived tokens with no standalone Dart literal (documented gaps).
const SKIP = new Set([
  '--memox-font-sans', // family stack -> only first family surfaced (consumed)
  '--memox-ring-focus', // `0 0 0 3px var(--memox-focus-ring)` — derived ring, built at use site from focusRing
]);

// ── run ─────────────────────────────────────────────────────────────────────
loadTokens();
emitColors();
emitSpacing();
emitRadius();
emitTypography();
emitSizes();
emitElevation();
emitMotion();

const unconsumed = [...TOK.keys()].filter((n) => !CONSUMED.has(n) && !SKIP.has(n));
if (unconsumed.length) {
  console.error(`✗ ${unconsumed.length} kit token(s) not mirrored by any emitter:`);
  for (const n of unconsumed) console.error(`    ${n}  (${TOK.get(n)._file})`);
  console.error(`  Add an emitter mapping, or list in SKIP with a reason.`);
  process.exit(1);
}

if (!CHECK) mkdirSync(OUT_DIR, { recursive: true });
let drift = 0;
for (const [name, content] of Object.entries(FILES)) {
  const path = join(OUT_DIR, name);
  let existing = null;
  try { existing = readFileSync(path, 'utf8'); } catch { /* new file */ }
  if (existing === content) continue;
  drift++;
  if (CHECK) {
    console.error(`✗ out of date: lib/core/theme/${name}`);
  } else {
    writeFileSync(path, content);
    console.log(`${existing === null ? 'created' : 'updated'}  lib/core/theme/${name}`);
  }
}

if (CHECK && drift) {
  console.error(`\n${drift} token file(s) out of date. Run: node tool/design/gen_tokens.mjs`);
  process.exit(1);
}
console.log(
  CHECK
    ? `✓ token files up to date (${TOK.size} tokens, ${Object.keys(FILES).length} files)`
    : `✓ ${TOK.size} tokens -> ${Object.keys(FILES).length} files${drift ? '' : ' (no changes)'}`,
);
