// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'game_recall_before_reveal_fixture.dart';
import 'game_recall_complete_fixture.dart';
import 'game_recall_forgot_fixture.dart';
import 'game_recall_remembered_fixture.dart';
import 'game_recall_revealed_fixture.dart';

/// State fixtures for the game-recall screen, keyed by matrix state name.
final Map<String, StateFixture> gameRecallFixtures = {
  'before-reveal': gameRecallBeforeRevealFixture,
  'revealed': gameRecallRevealedFixture,
  'remembered': gameRecallRememberedFixture,
  'forgot': gameRecallForgotFixture,
  'complete': gameRecallCompleteFixture,
};
