// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'player_end_fixture.dart';
import 'player_paused_fixture.dart';
import 'player_playing_fixture.dart';
import 'player_speed_fixture.dart';

/// State fixtures for the player screen, keyed by matrix state name.
final Map<String, StateFixture> playerFixtures = {
  'playing': playerPlayingFixture,
  'paused': playerPausedFixture,
  'speed': playerSpeedFixture,
  'end': playerEndFixture,
};
