// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'theme_accent_size_fixture.dart';
import 'theme_dark_fixture.dart';
import 'theme_light_fixture.dart';

/// State fixtures for the theme screen, keyed by matrix state name.
final Map<String, StateFixture> themeFixtures = {
  'light': themeLightFixture,
  'dark': themeDarkFixture,
  'accent-size': themeAccentSizeFixture,
};
