// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'import_done_fixture.dart';
import 'import_dup_warning_fixture.dart';
import 'import_mapping_fixture.dart';
import 'import_preview_fixture.dart';
import 'import_source_fixture.dart';

/// State fixtures for the import screen, keyed by matrix state name.
final Map<String, StateFixture> importFixtures = {
  'source': importSourceFixture,
  'mapping': importMappingFixture,
  'preview': importPreviewFixture,
  'dup-warning': importDupWarningFixture,
  'done': importDoneFixture,
};
