// GENERATED by tool/golden/scaffold.mjs — then FILLED BY HAND. Once you replace the sentinel below with a
// real StateFixture, the scaffolder leaves this file untouched on re-run.
// game-mc · complete — golden-parity fixture (docs/agent/golden-parity/WBS.md).
import '../_fixture.dart';

// FILL(golden-parity): replace the sentinel with a real StateFixture(overrides, drive, contentMask).
const StateFixture gameMcCompleteFixture = StateFixture.unimplemented(
  'game-mc/complete',
);
