// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'game_mc_complete_fixture.dart';
import 'game_mc_correct_fixture.dart';
import 'game_mc_waiting_fixture.dart';
import 'game_mc_wrong_fixture.dart';

/// State fixtures for the game-mc screen, keyed by matrix state name.
final Map<String, StateFixture> gameMcFixtures = {
  'waiting': gameMcWaitingFixture,
  'correct': gameMcCorrectFixture,
  'wrong': gameMcWrongFixture,
  'complete': gameMcCompleteFixture,
};
