// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'export_config_fixture.dart';
import 'export_done_fixture.dart';
import 'export_exporting_fixture.dart';

/// State fixtures for the export screen, keyed by matrix state name.
final Map<String, StateFixture> exportFixtures = {
  'config': exportConfigFixture,
  'exporting': exportExportingFixture,
  'done': exportDoneFixture,
};
