import 'dart:convert';
import 'dart:io';

import 'package:drift/drift.dart' show Value;
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:memox_v4/app/di/clock_provider.dart';
import 'package:memox_v4/app/di/database_provider.dart';
import 'package:memox_v4/core/theme/app_theme.dart';
import 'package:memox_v4/core/util/clock.dart';
import 'package:memox_v4/core/util/day_key.dart';
import 'package:memox_v4/data/datasources/local/connection/database_connection.dart';
import 'package:memox_v4/data/datasources/local/drift/app_database.dart';
import 'package:memox_v4/l10n/generated/app_localizations.dart';
import 'package:memox_v4/presentation/features/engagement/screens/dashboard_screen.dart';
import 'package:memox_v4/presentation/shared/widgets/display/mx_text.dart';
import 'package:memox_v4/presentation/shared/widgets/surfaces/mx_card.dart';

/// Deterministic parity gate (POC) for the dashboard, driven by the contract the
/// TOOLS produce, not by hand:
///  - `tool/parity/contracts/dashboard.gen.json` — generated by
///    `gen_parity_contract.mjs` (static kit-JSX parse): key + component + variant.
///  - `tool/parity/contracts/dashboard.slots.json` — curated slot bindings (role +
///    l10n/bind), the layer not derivable from static JSX.
///
/// Three layers, all asserted on typed props/strings (no pixels, no AI):
///  1. IDENTITY — every keyed MxCard node renders.
///  2. STYLING  — its `variant` matches the kit (⇒ bg/radius/border, owned by MxCard).
///  3. SLOTS    — each slot renders an [MxText] with the bound [MxTextRole]; `l10n`
///                slots also assert the localized copy.
///
/// Non-MxCard nodes the generator found (appbar, start, decks-head…) are not yet
/// keyed in the FE — that is the identity-rollout gap, intentionally not gated here.
class _FixedClock implements Clock {
  _FixedClock(this._now);
  final DateTime _now;
  @override
  DateTime now() => _now;
  @override
  DateTime nowUtc() => _now.toUtc();
}

const Map<String, MxCardVariant> _variants = <String, MxCardVariant>{
  'elevated': MxCardVariant.elevated,
  'flat': MxCardVariant.flat,
  'muted': MxCardVariant.muted,
  'primary': MxCardVariant.primary,
  'primarySoft': MxCardVariant.primarySoft,
};

MxTextRole _role(String name) =>
    MxTextRole.values.firstWhere((r) => r.name == name);

/// Resolve an l10n key to its localized string. A future generator emits exactly
/// the keys a screen's slots reference; the POC's seven are listed by hand.
String _l10n(AppLocalizations l, String key) => switch (key) {
  'dashboardTodayLabel' => l.dashboardTodayLabel,
  'dashboardTimeStudiedLabel' => l.dashboardTimeStudiedLabel,
  'dashboardWordsLearned' => l.dashboardWordsLearned,
  'dashboardGoalTitle' => l.dashboardGoalTitle,
  'dashboardGoalHint' => l.dashboardGoalHint,
  'dashboardDayStreak' => l.dashboardDayStreak,
  'dashboardMasteredLabel' => l.dashboardMasteredLabel,
  _ => throw ArgumentError('no l10n resolver for "$key"'),
};

Map<String, dynamic> _readJson(String path) =>
    jsonDecode(File(path).readAsStringSync()) as Map<String, dynamic>;

void main() {
  late AppDatabase db;
  late int pairId;
  final today = DateTime(2026, 6, 28, 10);

  final nodes =
      (_readJson('tool/parity/contracts/dashboard.gen.json')['nodes']
              as List<dynamic>)
          .cast<Map<String, dynamic>>();
  final slotMap =
      _readJson('tool/parity/contracts/dashboard.slots.json')['slots']
          as Map<String, dynamic>;

  setUp(() async {
    db = AppDatabase.forTesting(openInMemoryDatabase());
    pairId = await db
        .into(db.languagePair)
        .insert(
          LanguagePairCompanion.insert(sourceLang: 'ko', targetLang: 'vi'),
        );
  });
  tearDown(() => db.close());

  Widget host() => ProviderScope(
    overrides: [
      databaseProvider.overrideWithValue(db),
      clockProvider.overrideWithValue(_FixedClock(today)),
    ],
    child: MaterialApp(
      theme: AppTheme.light(),
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      home: const Scaffold(body: DashboardScreen()),
    ),
  );

  // Drive the goal-met state so all four singleton cards render.
  Future<void> pumpGoalMet(WidgetTester tester) async {
    await db
        .into(db.settings)
        .insert(
          SettingsCompanion.insert(
            key: 'daily_goal_words',
            value: const Value('5'),
          ),
        );
    await db
        .into(db.dailyActivity)
        .insert(
          DailyActivityCompanion.insert(
            day: dayKey(today),
            pairId: pairId,
            seconds: const Value(120),
            words: const Value(7),
          ),
        );
    await tester.pumpWidget(host());
    await tester.pumpAndSettle();
  }

  testWidgets('generated contract: identity + variant + slot bindings', (
    tester,
  ) async {
    await pumpGoalMet(tester);
    final l10n = AppLocalizations.of(
      tester.element(find.byType(DashboardScreen)),
    );

    for (final node in nodes) {
      // The FE keys only MxCard nodes in this POC; others await identity rollout.
      if (node['component'] != 'MxCard') continue;
      final key = node['key'] as String;
      final finder = find.byKey(ValueKey(key));

      // 1. IDENTITY.
      expect(finder, findsOneWidget, reason: '$key not rendered');

      // 2. STYLING (variant ⇒ bg/radius/border).
      final expectedVariant = _variants[node['variant'] as String];
      expect(expectedVariant, isNotNull, reason: 'unknown variant for $key');
      expect(
        tester.widget<MxCard>(finder).variant,
        expectedVariant,
        reason: '$key variant drifted from contract',
      );

      // 3. SLOTS (curated overlay).
      final slots = (slotMap[key] as List<dynamic>? ?? <dynamic>[])
          .cast<Map<String, dynamic>>();
      for (final slot in slots) {
        final name = slot['name'] as String;
        final role = _role(slot['role'] as String);

        if (slot.containsKey('l10n')) {
          final text = _l10n(l10n, slot['l10n'] as String);
          expect(
            find.descendant(
              of: finder,
              matching: find.byWidgetPredicate(
                (w) => w is MxText && w.data == text && w.role == role,
              ),
            ),
            findsOneWidget,
            reason:
                '$key slot "$name": MxText(role:${role.name}) "$text" absent',
          );
        } else {
          expect(
            find.descendant(
              of: finder,
              matching: find.byWidgetPredicate(
                (w) => w is MxText && w.role == role,
              ),
            ),
            findsWidgets,
            reason: '$key slot "$name": no MxText(role:${role.name})',
          );
        }
      }
    }
  });
}
