// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'search_empty_recent_fixture.dart';
import 'search_filtered_fixture.dart';
import 'search_loading_fixture.dart';
import 'search_no_results_fixture.dart';
import 'search_results_fixture.dart';

/// State fixtures for the search screen, keyed by matrix state name.
final Map<String, StateFixture> searchFixtures = {
  'empty-recent': searchEmptyRecentFixture,
  'loading': searchLoadingFixture,
  'results': searchResultsFixture,
  'filtered': searchFilteredFixture,
  'no-results': searchNoResultsFixture,
};
