// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'settings_group_expanded_fixture.dart';
import 'settings_loaded_fixture.dart';
import 'settings_value_picker_fixture.dart';

/// State fixtures for the settings screen, keyed by matrix state name.
final Map<String, StateFixture> settingsFixtures = {
  'loaded': settingsLoadedFixture,
  'group-expanded': settingsGroupExpandedFixture,
  'value-picker': settingsValuePickerFixture,
};
