// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'flashcard_editor_audio_fixture.dart';
import 'flashcard_editor_create_fixture.dart';
import 'flashcard_editor_duplicate_fixture.dart';
import 'flashcard_editor_edit_fixture.dart';
import 'flashcard_editor_multi_meaning_fixture.dart';
import 'flashcard_editor_validation_fixture.dart';

/// State fixtures for the flashcard-editor screen, keyed by matrix state name.
final Map<String, StateFixture> flashcardEditorFixtures = {
  'create': flashcardEditorCreateFixture,
  'edit': flashcardEditorEditFixture,
  'multi-meaning': flashcardEditorMultiMeaningFixture,
  'audio': flashcardEditorAudioFixture,
  'duplicate': flashcardEditorDuplicateFixture,
  'validation': flashcardEditorValidationFixture,
};
