// GENERATED by tool/golden/scaffold.mjs — then FILLED BY HAND. Once you replace the sentinel below with a
// real StateFixture, the scaffolder leaves this file untouched on re-run.
// study-session · stage1-review — golden-parity fixture (docs/agent/golden-parity/WBS.md).
import '../_fixture.dart';

// FILL(golden-parity): replace the sentinel with a real StateFixture(overrides, drive, contentMask).
const StateFixture studySessionStage1ReviewFixture = StateFixture.unimplemented(
  'study-session/stage1-review',
);
