// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'study_session_answer_save_error_fixture.dart';
import 'study_session_due_review_fixture.dart';
import 'study_session_exit_fixture.dart';
import 'study_session_relearn_fixture.dart';
import 'study_session_resume_error_fixture.dart';
import 'study_session_resume_fixture.dart';
import 'study_session_stage1_review_fixture.dart';
import 'study_session_stage2_matching_fixture.dart';
import 'study_session_stage3_choice_fixture.dart';
import 'study_session_stage4_recall_fixture.dart';
import 'study_session_stage5_typing_fixture.dart';

/// State fixtures for the study-session screen, keyed by matrix state name.
final Map<String, StateFixture> studySessionFixtures = {
  'due-review': studySessionDueReviewFixture,
  'stage1-review': studySessionStage1ReviewFixture,
  'stage2-matching': studySessionStage2MatchingFixture,
  'stage3-choice': studySessionStage3ChoiceFixture,
  'stage4-recall': studySessionStage4RecallFixture,
  'stage5-typing': studySessionStage5TypingFixture,
  'relearn': studySessionRelearnFixture,
  'resume': studySessionResumeFixture,
  'resume-error': studySessionResumeErrorFixture,
  'answer-save-error': studySessionAnswerSaveErrorFixture,
  'exit': studySessionExitFixture,
};
