// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'dashboard_empty_fixture.dart';
import 'dashboard_goal_met_fixture.dart';
import 'dashboard_loaded_fixture.dart';
import 'dashboard_loading_fixture.dart';
import 'dashboard_not_studied_fixture.dart';
import 'dashboard_streak_reset_fixture.dart';

/// State fixtures for the dashboard screen, keyed by matrix state name.
final Map<String, StateFixture> dashboardFixtures = {
  'loading': dashboardLoadingFixture,
  'empty': dashboardEmptyFixture,
  'not-studied': dashboardNotStudiedFixture,
  'loaded': dashboardLoadedFixture,
  'goal-met': dashboardGoalMetFixture,
  'streak-reset': dashboardStreakResetFixture,
};
