// GENERATED by tool/golden/scaffold.mjs — golden test (create-if-missing; safe to edit after generation).
@Tags(['golden-parity'])
library;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:memox_v4/core/theme/app_theme.dart';
import 'package:memox_v4/presentation/features/dashboard/screens/dashboard_screen.dart';
import '../../../fixtures/dashboard/dashboard_fixtures.dart';
import '../../support/screen_golden.dart';

/// Screen goldens for dashboard — one per state × theme, driven by the
/// state fixtures. Tagged 'golden-parity' (excluded from the default gate;
/// a dedicated CI job owns the baselines). Un-filled fixtures fail fast.
void main() {
  final themes = <String, ThemeData>{
    'light': AppTheme.light,
    'dark': AppTheme.dark,
  };
  dashboardFixtures.forEach((state, fixture) {
    themes.forEach((theme, data) {
      testWidgets('dashboard--$state--$theme', (tester) async {
        await pumpScreenGolden(
          tester,
          home: const DashboardScreen(),
          fixture: fixture,
          theme: data,
        );
        await expectLater(
          find.byType(MaterialApp),
          matchesGoldenFile(
            '../../goldens/screens/dashboard--$state--$theme.png',
          ),
        );
      });
    });
  });
}
