// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'statistics_insufficient_fixture.dart';
import 'statistics_loaded_fixture.dart';
import 'statistics_loading_fixture.dart';
import 'statistics_scope_switch_fixture.dart';

/// State fixtures for the statistics screen, keyed by matrix state name.
final Map<String, StateFixture> statisticsFixtures = {
  'loading': statisticsLoadingFixture,
  'loaded': statisticsLoadedFixture,
  'insufficient': statisticsInsufficientFixture,
  'scope-switch': statisticsScopeSwitchFixture,
};
