// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'game_typing_complete_fixture.dart';
import 'game_typing_correct_fixture.dart';
import 'game_typing_hint_fixture.dart';
import 'game_typing_typing_fixture.dart';
import 'game_typing_waiting_fixture.dart';
import 'game_typing_wrong_fixture.dart';

/// State fixtures for the game-typing screen, keyed by matrix state name.
final Map<String, StateFixture> gameTypingFixtures = {
  'waiting': gameTypingWaitingFixture,
  'typing': gameTypingTypingFixture,
  'hint': gameTypingHintFixture,
  'correct': gameTypingCorrectFixture,
  'wrong': gameTypingWrongFixture,
  'complete': gameTypingCompleteFixture,
};
