#!/usr/bin/env node
// tool/parity/gen_convert_prompts.mjs — stamp a per-screen JSX→Flutter conversion
// prompt (from convert-prompt.template.md) for every screen in the SCREENS registry,
// plus a queue README a /loop can walk one screen at a time.
//
// Usage:  node tool/parity/gen_convert_prompts.mjs

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PATHS } from '../_config.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '..', '..');
const KIT = join(REPO, PATHS.uiKitDir);
const LIB = join(REPO, 'lib', 'presentation', 'features');
const OUT = join(REPO, 'docs', 'agent', 'kit-to-flutter');
const TEMPLATE = readFileSync(join(HERE, 'convert-prompt.template.md'), 'utf8');

// Ordered [{ id, states }] from the SCREENS registry literal in index.html.
function registry() {
  const html = readFileSync(join(KIT, 'index.html'), 'utf8');
  const out = [];
  const re = /\{\s*id:\s*'([^']+)'[\s\S]*?states:\s*\[([^\]]+)\]/g;
  let m;
  while ((m = re.exec(html)) !== null) {
    out.push({ id: m[1], states: m[2].split(',').map((s) => s.trim().replace(/^'|'$/g, '')).filter(Boolean) });
  }
  return out;
}

function walk(dir, acc = []) {
  if (!existsSync(dir)) return acc;
  for (const n of readdirSync(dir)) {
    const p = join(dir, n);
    if (statSync(p).isDirectory()) walk(p, acc);
    else if (n.endsWith('.dart')) acc.push(p);
  }
  return acc;
}

const DART = walk(LIB);
// Resolve a screen's FE feature + file: the .dart that keys `mx-node:<screen>/…`,
// preferring a *_screen.dart. Returns { feature, file } relative to features/.
function resolveFe(screen) {
  const hits = DART.filter((f) => readFileSync(f, 'utf8').includes(`ValueKey('mx-node:${screen}/`));
  const pick = hits.find((f) => /screen.*\.dart$/.test(f)) || hits[0];
  if (!pick) return { feature: '(resolve manually — no keyed FE file found)', file: '(resolve manually)' };
  const rel = pick.slice(LIB.length + 1).split(/[\\/]/).join('/');
  return { feature: rel.split('/')[0], file: rel };
}

const snake = (s) => s.replace(/-/g, '_');

if (!existsSync(OUT)) mkdirSync(OUT, { recursive: true });

const screens = registry();
const queue = [];
screens.forEach((sc, i) => {
  const nn = String(i + 1).padStart(2, '0');
  const { feature, file } = resolveFe(sc.id);
  const md = TEMPLATE
    .replace(/\{\{SCREEN\}\}/g, sc.id)
    .replace(/\{\{SCREEN_SNAKE\}\}/g, snake(sc.id))
    .replace(/\{\{FEATURE\}\}/g, feature)
    .replace(/\{\{FILE\}\}/g, file)
    .replace(/\{\{STATES\}\}/g, sc.states.map((s) => `\`${s}\``).join(' · '))
    .replace(/\{\{NN\}\}/g, nn);
  const fname = `${nn}-${sc.id}.md`;
  writeFileSync(join(OUT, fname), md);
  queue.push({ nn, id: sc.id, feature, states: sc.states.length, fname });
});

// Queue README — the checklist a /loop walks, one screen per iteration.
const done = new Set(['dashboard', 'review']); // already have curated slots/states + parity test
const readme = [
  '# Kit → Flutter — conversion queue',
  '',
  'Per-screen prompts generated by `tool/parity/gen_convert_prompts.mjs` from',
  '`tool/parity/convert-prompt.template.md`. Each `NN-<screen>.md` is self-contained.',
  '',
  '## How to run (loop)',
  '',
  'Dynamic-mode loop, one screen per iteration:',
  '',
  '> `/loop` Đọc `docs/agent/kit-to-flutter/README.md`, chọn màn **pending** đầu tiên (ô `[ ]`),',
  '> đọc + thực thi ĐẦY ĐỦ file prompt của màn đó (baseline → verify --full → commit → push),',
  '> rồi đổi ô đó thành `[x]`. Mỗi vòng đúng 1 màn. Nếu prompt bảo DỪNG (drift/divergence) →',
  '> dừng, báo, chờ người. Hết pending → báo hoàn tất.',
  '',
  '`dashboard` + `review` đã có slots/states + parity test (2 màn mẫu) → đánh dấu sẵn `[x]`.',
  '',
  '## Queue',
  '',
  ...queue.map((q) => `- [${done.has(q.id) ? 'x' : ' '}] \`${q.fname}\` — **${q.id}** · feature \`${q.feature}\` · ${q.states} state(s)`),
  '',
];
writeFileSync(join(OUT, 'README.md'), readme.join('\n') + '\n');

console.log(`wrote ${screens.length} prompt(s) + README → docs/agent/kit-to-flutter/`);
