// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '_fixture.dart';
import 'dashboard/dashboard_fixtures.dart';
import 'deck-detail/deck_detail_fixtures.dart';
import 'drawer/drawer_fixtures.dart';
import 'export/export_fixtures.dart';
import 'flashcard-editor/flashcard_editor_fixtures.dart';
import 'game-matching/game_matching_fixtures.dart';
import 'game-mc/game_mc_fixtures.dart';
import 'game-picker/game_picker_fixtures.dart';
import 'game-recall/game_recall_fixtures.dart';
import 'game-typing/game_typing_fixtures.dart';
import 'import/import_fixtures.dart';
import 'library/library_fixtures.dart';
import 'player/player_fixtures.dart';
import 'reminder/reminder_fixtures.dart';
import 'review/review_fixtures.dart';
import 'search/search_fixtures.dart';
import 'settings/settings_fixtures.dart';
import 'statistics/statistics_fixtures.dart';
import 'study-result/study_result_fixtures.dart';
import 'study-session/study_session_fixtures.dart';
import 'theme/theme_fixtures.dart';

/// screen id → { state name → StateFixture }. Source of truth:
/// docs/design/screen-state-matrix.md (via tool/golden/scaffold.mjs).
final Map<String, Map<String, StateFixture>> stateRegistry = {
  'dashboard': dashboardFixtures,
  'library': libraryFixtures,
  'deck-detail': deckDetailFixtures,
  'search': searchFixtures,
  'settings': settingsFixtures,
  'drawer': drawerFixtures,
  'reminder': reminderFixtures,
  'theme': themeFixtures,
  'statistics': statisticsFixtures,
  'import': importFixtures,
  'export': exportFixtures,
  'flashcard-editor': flashcardEditorFixtures,
  'game-picker': gamePickerFixtures,
  'game-matching': gameMatchingFixtures,
  'game-mc': gameMcFixtures,
  'game-recall': gameRecallFixtures,
  'game-typing': gameTypingFixtures,
  'review': reviewFixtures,
  'player': playerFixtures,
  'study-session': studySessionFixtures,
  'study-result': studyResultFixtures,
};
