// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'game_picker_default_fixture.dart';
import 'game_picker_not_enough_fixture.dart';
import 'game_picker_scope_dropdown_fixture.dart';

/// State fixtures for the game-picker screen, keyed by matrix state name.
final Map<String, StateFixture> gamePickerFixtures = {
  'default': gamePickerDefaultFixture,
  'not-enough': gamePickerNotEnoughFixture,
  'scope-dropdown': gamePickerScopeDropdownFixture,
};
