// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'drawer_add_language_fixture.dart';
import 'drawer_open_fixture.dart';
import 'drawer_remove_language_fixture.dart';

/// State fixtures for the drawer screen, keyed by matrix state name.
final Map<String, StateFixture> drawerFixtures = {
  'open': drawerOpenFixture,
  'add-language': drawerAddLanguageFixture,
  'remove-language': drawerRemoveLanguageFixture,
};
