// GENERATED by tool/design/gen_tokens.mjs — DO NOT EDIT BY HAND.
// Source of truth: docs/design/MemoX Design System/tokens/colors.css
// Regenerate: node tool/design/gen_tokens.mjs
import 'package:flutter/widgets.dart';

/// Semantic color palette for one brightness, mirroring `--memox-<role>`
/// in `tokens/colors.css`. One [MxColors] per theme: [light] and [dark].
///
/// Features read colors from the theme, never raw `Color(0x...)`. The roles
/// Material's [ColorScheme] cannot express are surfaced via a theme extension
/// (Tier 1); the rest seed the [ColorScheme].
@immutable
class MxColors {
  const MxColors({
    required this.bg,
    required this.surface,
    required this.surfaceMuted,
    required this.surfaceRaised,
    required this.surfaceSunken,
    required this.text,
    required this.textSecondary,
    required this.textTertiary,
    required this.primary,
    required this.primaryStrong,
    required this.onPrimary,
    required this.primarySoft,
    required this.onPrimarySoft,
    required this.accent,
    required this.onAccent,
    required this.accentSoft,
    required this.border,
    required this.borderStrong,
    required this.divider,
    required this.success,
    required this.onSuccess,
    required this.successSoft,
    required this.onSuccessSoft,
    required this.warning,
    required this.onWarning,
    required this.warningSoft,
    required this.onWarningSoft,
    required this.error,
    required this.onError,
    required this.errorSoft,
    required this.onErrorSoft,
    required this.info,
    required this.onInfo,
    required this.infoSoft,
    required this.onInfoSoft,
    required this.stateHover,
    required this.statePressed,
    required this.stateSelected,
    required this.focusRing,
    required this.overlay,
  });

  final Color bg;
  final Color surface;
  final Color surfaceMuted;
  final Color surfaceRaised;
  final Color surfaceSunken;
  final Color text;
  final Color textSecondary;
  final Color textTertiary;
  final Color primary;
  final Color primaryStrong;
  final Color onPrimary;
  final Color primarySoft;
  final Color onPrimarySoft;
  final Color accent;
  final Color onAccent;
  final Color accentSoft;
  final Color border;
  final Color borderStrong;
  final Color divider;
  final Color success;
  final Color onSuccess;
  final Color successSoft;
  final Color onSuccessSoft;
  final Color warning;
  final Color onWarning;
  final Color warningSoft;
  final Color onWarningSoft;
  final Color error;
  final Color onError;
  final Color errorSoft;
  final Color onErrorSoft;
  final Color info;
  final Color onInfo;
  final Color infoSoft;
  final Color onInfoSoft;
  final Color stateHover;
  final Color statePressed;
  final Color stateSelected;
  final Color focusRing;
  final Color overlay;

  /// Brand primary seed (`--memox-primary`, light).
  static const Color seed = Color(0xFF4F46E5);

  // Selectable accent hues (theme-independent) — `--memox-palette-*`.
  static const Color paletteIndigo = Color(0xFF5569FF);
  static const Color paletteViolet = Color(0xFF7C5CFF);
  static const Color paletteGreen = Color(0xFF2BB673);
  static const Color paletteCoral = Color(0xFFFF6B6B);
  static const Color paletteAmber = Color(0xFFFF9F43);
  static const Color paletteCyan = Color(0xFF22A3C3);

  /// Light — `:root` / `[data-theme='light']`.
  static const MxColors light = MxColors(
    bg: Color(0xFFF3F4FB),
    surface: Color(0xFFFFFFFF),
    surfaceMuted: Color(0xFFECEDF8),
    surfaceRaised: Color(0xFFFFFFFF),
    surfaceSunken: Color(0xFFE3E5F4),
    text: Color(0xFF1D2240),
    textSecondary: Color(0xA81D2240),
    textTertiary: Color(0x8C1D2240),
    primary: Color(0xFF4F46E5),
    primaryStrong: Color(0xFF3F37C4),
    onPrimary: Color(0xFFFFFFFF),
    primarySoft: Color(0xFFE6E6FB),
    onPrimarySoft: Color(0xFF382FB4),
    accent: Color(0xFF1FA9D6),
    onAccent: Color(0xFF04303F),
    accentSoft: Color(0xFFDDF2FA),
    border: Color(0xFFE4E4F2),
    borderStrong: Color(0xFFCCCCE8),
    divider: Color(0x141D2240),
    success: Color(0xFF1A7D31),
    onSuccess: Color(0xFFFFFFFF),
    successSoft: Color(0xFFE0F4E2),
    onSuccessSoft: Color(0xFF1F7A33),
    warning: Color(0xFFF5920B),
    onWarning: Color(0xFF3A2200),
    warningSoft: Color(0xFFFDECCA),
    onWarningSoft: Color(0xFF93570A),
    error: Color(0xFFD91E44),
    onError: Color(0xFFFFFFFF),
    errorSoft: Color(0xFFFCE0E5),
    onErrorSoft: Color(0xFFC20F32),
    info: Color(0xFF1FA9D6),
    onInfo: Color(0xFF04303F),
    infoSoft: Color(0xFFDDF2FA),
    onInfoSoft: Color(0xFF0A6F93),
    stateHover: Color(0x0B1D2240),
    statePressed: Color(0x171D2240),
    stateSelected: Color(0x1A4F46E5),
    focusRing: Color(0x6B4F46E5),
    overlay: Color(0x7312142D),
  );

  /// Dark — `[data-theme='dark']`.
  static const MxColors dark = MxColors(
    bg: Color(0xFF0A0C1E),
    surface: Color(0xFF181C34),
    surfaceMuted: Color(0xFF14182F),
    surfaceRaised: Color(0xFF242A47),
    surfaceSunken: Color(0xFF070817),
    text: Color(0xFFECEDF7),
    textSecondary: Color(0xFFA7ABC6),
    textTertiary: Color(0xB3A7ABC6),
    primary: Color(0xFF4B42B8),
    primaryStrong: Color(0xFF8B83F4),
    onPrimary: Color(0xFFFFFFFF),
    primarySoft: Color(0xFF232452),
    onPrimarySoft: Color(0xFFC7C4F8),
    accent: Color(0xFF33C2FF),
    onAccent: Color(0xFF04303F),
    accentSoft: Color(0xFF123544),
    border: Color(0xFF2B3052),
    borderStrong: Color(0xFF3C4068),
    divider: Color(0x14FFFFFF),
    success: Color(0xFF57CA22),
    onSuccess: Color(0xFF06320F),
    successSoft: Color(0xFF173620),
    onSuccessSoft: Color(0xFF8EE06A),
    warning: Color(0xFFFFA319),
    onWarning: Color(0xFF2A1A00),
    warningSoft: Color(0xFF382909),
    onWarningSoft: Color(0xFFFFC25C),
    error: Color(0xFFFF1943),
    onError: Color(0xFFFFFFFF),
    errorSoft: Color(0xFF3B1622),
    onErrorSoft: Color(0xFFFF8A9C),
    info: Color(0xFF33C2FF),
    onInfo: Color(0xFF04303F),
    infoSoft: Color(0xFF123544),
    onInfoSoft: Color(0xFF82D6FB),
    stateHover: Color(0x0FFFFFFF),
    statePressed: Color(0x1CFFFFFF),
    stateSelected: Color(0x3D7D74F0),
    focusRing: Color(0x997D74F0),
    overlay: Color(0xA8000000),
  );
}
