// GENERATED by tool/design/gen_tokens.mjs — DO NOT EDIT BY HAND.
// Source of truth: docs/design/MemoX Design System/tokens/component.css / opacity.css
// Regenerate: node tool/design/gen_tokens.mjs
/// Per-component intrinsic dimensions (`--memox-comp-*`) and the opacity
/// scale (`--memox-opacity-*`). Theme-independent (K.1 full tokenization).
library;

/// Fixed control dimensions (`--memox-comp-<component>-<prop>`).
abstract final class MxComponentSizes {
  const MxComponentSizes._();

  static const double chipHeight = 34;
  static const double switchWidth = 52;
  static const double switchHeight = 32;
  static const double switchThumb = 22;
  static const double switchThumbOn = 24;
  static const double switchThumbInset = 4;
  static const double switchThumbInsetOn = 2;
  static const double switchThumbTravel = 20;
  static const double badgeHeight = 20;
  static const double badgeMinWidth = 20;
  static const double badgePadX = 6;
  static const double badgeGap = 4;
  static const double badgeDot = 10;
  static const double avatarSm = 32;
  static const double avatarMd = 44;
  static const double avatarLg = 64;
  static const double iconTileMd = 48;
  static const double iconTileLg = 60;
  static const double iconBtnSm = 36;
  static const double searchDockHeight = 52;
  static const double navPillWidth = 56;
  static const double navPillHeight = 30;
  static const double navItemGap = 3;
  static const double navSafePad = 4;
  static const double segmentedSegHeight = 40;
}

/// Opacity scale (`--memox-opacity-*`): disabled controls, muted rows,
/// sub-labels on tinted surfaces.
abstract final class MxOpacity {
  const MxOpacity._();

  static const double disabled = 0.45;
  static const double half = 0.5;
  static const double muted = 0.55;
  static const double labelSoft = 0.85;
  static const double label = 0.9;
}
