// GENERATED by tool/design/gen_tokens.mjs — DO NOT EDIT BY HAND.
// Source of truth: docs/design/MemoX Design System/tokens/motion.css
// Regenerate: node tool/design/gen_tokens.mjs
import 'package:flutter/animation.dart';

/// Motion tokens (durations + easings), mirroring `--memox-duration-*` and
/// `--memox-ease-*` in `tokens/motion.css`. Theme-independent.
abstract final class MxDurations {
  const MxDurations._();

  static const Duration fast = Duration(milliseconds: 140);
  static const Duration flash = Duration(milliseconds: 300);
  static const Duration pulse = Duration(milliseconds: 1300);
}

/// Easing curves (`--memox-ease-*`): standard / decelerate (enter) /
/// accelerate (exit).
abstract final class MxEasing {
  const MxEasing._();

  static const Cubic standard = Cubic(0.2, 0, 0, 1);
}
