// GENERATED by tool/design/gen_tokens.mjs — DO NOT EDIT BY HAND.
// Source of truth: docs/design/MemoX Design System/tokens/radius.css
// Regenerate: node tool/design/gen_tokens.mjs
import 'package:flutter/widgets.dart';

/// Corner-radius scale + role aliases, mirroring `--memox-radius-*` in
/// `tokens/radius.css`. Raw `double` steps plus ready [BorderRadius] roles.
abstract final class MxRadius {
  const MxRadius._();

  // scale
  static const double xs = 6;
  static const double sm = 10;
  static const double md = 14;
  static const double lg = 18;
  static const double xl = 24;
  static const double xxl = 28;

  // role aliases
  static const double card = 20;
  static const double tile = 16;
  static const double control = 12;
  static const double chip = 999;
  static const double pill = 999;
  static const double full = 9999;

  // ── BorderRadius helpers ──────────────────────────────────────────────────
  static const BorderRadius cardRadius =
      BorderRadius.all(Radius.circular(card));
  static const BorderRadius tileRadius =
      BorderRadius.all(Radius.circular(tile));
  static const BorderRadius controlRadius =
      BorderRadius.all(Radius.circular(control));
  static const BorderRadius pillRadius =
      BorderRadius.all(Radius.circular(pill));
}
