// GENERATED by tool/design/gen_tokens.mjs — DO NOT EDIT BY HAND.
// Source of truth: docs/design/MemoX Design System/tokens/spacing.css
// Regenerate: node tool/design/gen_tokens.mjs
/// Spacing scale (4px base) + layout rhythm, mirroring `--memox-space-*`
/// and the layout tokens in `tokens/spacing.css`. Theme-independent.
abstract final class MxSpacing {
  const MxSpacing._();

  static const double space1 = 4;
  static const double space2 = 8;
  static const double space3 = 12;
  static const double space4 = 16;
  static const double space5 = 20;
  static const double space6 = 24;
  static const double space7 = 32;
  static const double space8 = 40;

  // ── layout rhythm ─────────────────────────────────────────────────────────
  /// Screen edge padding on phones.
  static const double gutter = 20;

  /// Compact top app bar.
  static const double appBarHeight = 64;

  /// Large / hero app bar.
  static const double appBarLargeHeight = 112;

  /// Fixed bottom navigation.
  static const double bottomNavHeight = 72;

  /// Floating action button.
  static const double fabSize = 60;

  /// Minimum interactive target (a11y floor).
  static const double minTouchTarget = 48;
}
