// GENERATED by tool/design/gen_tokens.mjs — DO NOT EDIT BY HAND.
// Source of truth: docs/design/MemoX Design System/tokens/size.css / icon-size.css / stroke.css
// Regenerate: node tool/design/gen_tokens.mjs
/// Fixed-dimension scales, mirroring `--memox-size-*`, `--memox-icon-size-*`
/// and `--memox-stroke-*`. Theme-independent.
library;

/// Element size scale (`--memox-size-*`).
abstract final class MxSizes {
  const MxSizes._();

  static const double size3xs = 4;
  static const double size2xs = 8;
  static const double sizeXs = 16;
  static const double sizeSm = 40;
  static const double sizeMd = 56;
  static const double sizeLg = 74;
  static const double sizeXl = 96;
  static const double size2xl = 120;
  static const double size3xl = 220;
  static const double size4xl = 280;
  static const double size5xl = 320;
}

/// Icon glyph sizes (`--memox-icon-size-*`). 20/24 reuse the type scale.
abstract final class MxIconSize {
  const MxIconSize._();

  static const double sm = 18;
  static const double md = 22;
  static const double lg = 28;
}

/// Border / stroke widths (`--memox-stroke-*`).
abstract final class MxStroke {
  const MxStroke._();

  static const double hairline = 1;
  static const double emphasis = 2;
  static const double focus = 3;
}
