// GENERATED by tool/design/gen_tokens.mjs — DO NOT EDIT BY HAND.
// Source of truth: docs/design/MemoX Design System/tokens/typography.css
// Regenerate: node tool/design/gen_tokens.mjs
import 'package:flutter/widgets.dart';

/// Typography primitives, mirroring `--memox-font-*`, `--memox-line-height-*`
/// and `--memox-letter-spacing-*` in `tokens/typography.css`. Tier 1 composes
/// these into the Material [TextTheme].
///
/// Letter spacing is an **em multiplier** (the CSS unit); Flutter's
/// `letterSpacing` is logical px, so multiply by the slot size:
/// `letterSpacing: size * MxTypography.trackingTight`.
abstract final class MxTypography {
  const MxTypography._();

  /// Brand family (variable font under `.../fonts/`, wired via pubspec).
  static const String fontFamily = 'Plus Jakarta Sans';

  // ── font sizes ────────────────────────────────────────────────────────────
  static const double sizeXs = 12;
  static const double sizeSm = 13;
  static const double sizeBase = 15;
  static const double sizeMd = 17;
  static const double sizeLg = 20;
  static const double sizeXl = 24;
  static const double size2xl = 30;
  static const double size3xl = 38;
  static const double size4xl = 48;

  // ── weights ───────────────────────────────────────────────────────────────
  static const FontWeight regular = FontWeight.w400;
  static const FontWeight medium = FontWeight.w500;
  static const FontWeight semibold = FontWeight.w600;
  static const FontWeight bold = FontWeight.w700;
  static const FontWeight extrabold = FontWeight.w800;

  // ── line heights (unitless -> Flutter `height`) ───────────────────────────
  static const double lineHeightNone = 1;
  static const double lineHeightTight = 1.15;
  static const double lineHeightNormal = 1.5;

  // ── letter spacing (em multipliers — see class doc) ───────────────────────
  static const double trackingTight = -0.02;
  static const double trackingWide = 0.04;
}
