// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'deck_detail_add_menu_fixture.dart';
import 'deck_detail_card_actions_fixture.dart';
import 'deck_detail_deck_delete_confirm_fixture.dart';
import 'deck_detail_deck_menu_fixture.dart';
import 'deck_detail_delete_confirm_fixture.dart';
import 'deck_detail_empty_fixture.dart';
import 'deck_detail_error_fixture.dart';
import 'deck_detail_loaded_fixture.dart';
import 'deck_detail_loading_fixture.dart';
import 'deck_detail_move_fixture.dart';
import 'deck_detail_no_results_fixture.dart';
import 'deck_detail_reset_confirm_fixture.dart';
import 'deck_detail_search_fixture.dart';

/// State fixtures for the deck-detail screen, keyed by matrix state name.
final Map<String, StateFixture> deckDetailFixtures = {
  'loading': deckDetailLoadingFixture,
  'empty': deckDetailEmptyFixture,
  'error': deckDetailErrorFixture,
  'loaded': deckDetailLoadedFixture,
  'search': deckDetailSearchFixture,
  'no-results': deckDetailNoResultsFixture,
  'add-menu': deckDetailAddMenuFixture,
  'deck-menu': deckDetailDeckMenuFixture,
  'card-actions': deckDetailCardActionsFixture,
  'move': deckDetailMoveFixture,
  'delete-confirm': deckDetailDeleteConfirmFixture,
  'deck-delete-confirm': deckDetailDeckDeleteConfirmFixture,
  'reset-confirm': deckDetailResetConfirmFixture,
};
