// GENERATED by tool/golden/scaffold.mjs — golden test (create-if-missing; safe to edit after generation).
@Tags(['golden-parity'])
library;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:memox_v4/core/theme/app_theme.dart';
import 'package:memox_v4/presentation/features/deck-detail/screens/deck_detail_screen.dart';
import '../../../fixtures/deck-detail/deck_detail_fixtures.dart';
import '../../support/screen_golden.dart';

/// Screen goldens for deck-detail — one per state × theme, driven by the
/// state fixtures. Tagged 'golden-parity' (excluded from the default gate;
/// a dedicated CI job owns the baselines). Un-filled fixtures fail fast.
void main() {
  final themes = <String, ThemeData>{'light': AppTheme.light, 'dark': AppTheme.dark};
  deckDetailFixtures.forEach((state, fixture) {
    themes.forEach((theme, data) {
      testWidgets('deck-detail--$state--$theme', (tester) async {
        await pumpScreenGolden(tester, home: const DeckDetailScreen(deckId: 'deck-food'), fixture: fixture, theme: data);
        await expectLater(
          find.byType(MaterialApp),
          matchesGoldenFile('../../goldens/screens/deck-detail--$state--$theme.png'),
        );
      });
    });
  });
}
