// GENERATED by tool/golden/scaffold.mjs — DO NOT EDIT (pure aggregation; re-run the scaffolder).
import '../_fixture.dart';
import 'reminder_off_fixture.dart';
import 'reminder_on_fixture.dart';
import 'reminder_time_picker_fixture.dart';

/// State fixtures for the reminder screen, keyed by matrix state name.
final Map<String, StateFixture> reminderFixtures = {
  'off': reminderOffFixture,
  'on': reminderOnFixture,
  'time-picker': reminderTimePickerFixture,
};
